spring:
<<<<<<< HEAD
  datasource:
    url: jdbc:mysql://localhost:3306/bd-prueba
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
  application:
    name: grupo-12-OO2-2024
=======
    datasource:
        url:  jdbc:mysql://localhost:3306/bd_grupo12?serverTimezone=UTC
        username: ${USERNAME}
        password: ${PASSWORD}
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            dialect: org.hibernate.dialect.MySQL5Dialect
    thymeleaf:
        cache: false
    application:
        name: grupo-12-OO2-2024
>>>>>>> main
